# Generated by Django 2.2 on 2021-12-22 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_pay_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='discounts',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='plane',
        ),
        migrations.RemoveField(
            model_name='pay',
            name='discounts_applied',
        ),
        migrations.RemoveField(
            model_name='pay',
            name='partner',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.DeleteModel(
            name='Pay',
        ),
        migrations.DeleteModel(
            name='Plane',
        ),
    ]
